<template>
  <div class="activity-one-result">
    <img :src="resultData.goodObjectUrl" alt="" />
    <!-- TODO Remplacer par l'animation de fond -->
    <div class="bg-anim">
      <span v-for="index in 20" :key="index" class="big-title">{{
        resultData.answerWord.toUpperCase()
      }}</span>
    </div>

    <CustomButton
      @click.native="nextActivity"
      arrow-color="#FF6644"
      color="white"
      text="Passer à l'activité suivante"
    ></CustomButton>
  </div>
</template>

<script lang="ts">
import { Component, getModule, Prop, Vue } from "nuxt-property-decorator";
import GlobalSceneStore from "~/store/globalScene";
import ActivityStore from "~/store/activity";
import CustomButton from "~/components/buttons/CustomButton.vue";
import { ActivityOneResultData } from "~/core/types";
import { ACTIVITY_TYPE } from "~/core/enums";

@Component({
  components: {
    CustomButton
  }
})
export default class ActivityOneResult extends Vue {
  @Prop({ type: Object, required: true })
  readonly resultData!: ActivityOneResultData;

  public globalSceneStore = getModule(GlobalSceneStore, this.$store);
  public activityStore = getModule(ActivityStore, this.$store);

  public nextActivity() {
    this.activityStore.setCurrentActivity(ACTIVITY_TYPE.ACTIVITY_2);
  }
}
</script>

<style scoped lang="scss">
.activity-one-result {
  background: linear-gradient(107.28deg, #ff6644 29.48%, #ff9d6f 100%);
  width: 100%;
  height: 100%;
  display: flex;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  z-index: 30;

  .bg-anim {
    display: flex;
    position: absolute;
    animation: slide-left 40s ease-in-out infinite alternate both;

    span {
      color: white;
      margin: 0 50px;
    }
  }

  img {
    width: 500px;
    margin-bottom: 60px;
    z-index: 10;
    animation: slide-top 3s ease-in-out infinite alternate both;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-5-2 19:1:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
  100% {
    -webkit-transform: translateX(-25%);
    transform: translateX(-25%);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-5-2 18:44:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0) rotate(-1.5deg);
    transform: translateY(0) rotate(-1.5deg);
  }
  100% {
    -webkit-transform: translateY(-15px) rotate(1.5deg);
    transform: translateY(-15px) rotate(1.5deg);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0) rotate(-1.5deg);
    transform: translateY(0) rotate(-1.5deg);
  }
  100% {
    -webkit-transform: translateY(-15px) rotate(1.5deg);
    transform: translateY(-15px) rotate(1.5deg);
  }
}
</style>
