<template>
  <nuxt-link
    v-if="isVisible()"
    :style="style()"
    class="point point-0"
    :to="data.url"
  >
    <div :class="{isCompleted: isCompleted()}" class="center"></div>
  </nuxt-link>
</template>

<script lang="ts">
import {Component, getModule, Prop, Vue} from "nuxt-property-decorator";
import {InteractionPointConfig} from "~/core/types";
import GlobalModule from "~/store/global";
import AuthModule from "~/store/auth";

@Component
export default class InteractionPoints extends Vue {
  @Prop({type: Object, required: true})
  readonly data!: InteractionPointConfig;
  public globalModule: GlobalModule = getModule(GlobalModule, this.$store);
  public authModule: AuthModule = getModule(AuthModule, this.$store);

  public mounted() {}

  public style() {
    return `
    transform: translateX(${this.data.transformX}px) translateY(${
      this.data.transformY
    }px);
    `;
  }

  public isVisible() {
    return this.data.isVisible(this.globalModule, this.authModule);
  }

  public isCompleted() {
    console.log(this.data.isCompleted(this.globalModule))
    return this.data.isCompleted(this.globalModule)
  }
}
</script>

<style lang="scss" scoped>
.point {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 9;
  cursor: pointer;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: transparent !important;

  .center {
    height: 48px;
    width: 48px;
    background-color: rgba(255, 255, 255, 0.3);
    backdrop-filter: blur(5px);
    border-radius: 50%;
    border: 0.5px solid $dark-cream;
    display: flex;
    justify-content: center;
    align-items: center;

    &.isCompleted {
      background-color: rgb(43, 190, 32);
    }

    &:after {
      content: "";
      height: 78px;
      width: 78px;
      position: absolute;
      border-top: 1px solid $dark-cream;
      border-right: 1px solid $dark-cream;
      border-bottom: 1px solid rgba(255, 255, 255, 0.2);
      border-left: 1px solid rgba(255, 255, 255, 0.2);
      border-radius: 50%;
      animation: rotate-center 5s linear infinite both;
    }

    &:hover {
      &:before {
        content: "";
        height: 70px;
        width: 70px;
        background-color: rgba(255, 255, 255, 0.3);
        position: absolute;
        border: 1px solid $dark-cream;
        border-radius: 50%;
        animation: ping 0.8s ease-in-out infinite both;
      }
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-4-27 19:20:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
    transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-4-27 21:1:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation ping
 * ----------------------------------------
 */
@-webkit-keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
}
@keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
}
</style>
