<template>
  <div class="choice-card" :style="{ width: cardWidth() }">
    <img :src="image" alt="" :style="{ width: imgWidth() }" />
    <p class="choice-title big-title">{{ title }}</p>
    <span class="choice-description main-font"> <slot /> </span>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "nuxt-property-decorator";

@Component
export default class ChoiceCard extends Vue {
  @Prop({ type: String, required: true }) readonly title!: string;
  @Prop({ type: String, required: true }) readonly image!: string;
  @Prop({ type: Number, default: 360 }) readonly width!: number;
  @Prop({ type: Number, default: 270 }) readonly imageWidth!: number;

  cardWidth() {
    return `${this.width}px`;
  }

  imgWidth() {
    return `${this.imageWidth}px`;
  }
}
</script>

<style scoped lang="scss">
.choice-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  background: linear-gradient(
    120.55deg,
    rgba(255, 255, 255, 0.4) 0%,
    rgba(255, 255, 255, 0) 100%
  );
  border: 1px solid #fdebe2;
  border-radius: 32px;
  padding: 85px 45px 38px 45px;
  position: relative;
  justify-content: flex-end;
  transform: translate(0, 20%);

  img {
    position: absolute;
    top: -40%;
    animation: slide-top 3s ease-in-out infinite alternate both;
  }

  .choice-title {
    /* Titres */
    font-style: normal;
    font-weight: normal;
    font-size: 30px;
    line-height: 40px;
    font-family: $secondary_font;

    display: flex;
    align-items: center;
    text-align: center;

    /* Blue-dark */

    color: $dark-blue;

    mix-blend-mode: normal;
  }

  .choice-description {
    color: $dark-blue;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-5-2 18:44:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(0) rotate(-1.5deg);
    transform: translateY(0) rotate(-1.5deg);
  }
  100% {
    -webkit-transform: translateY(-15px) rotate(1.5deg);
    transform: translateY(-15px) rotate(1.5deg);
  }
}
@keyframes slide-top {
  0% {
    -webkit-transform: translateY(0) rotate(-1.5deg);
    transform: translateY(0) rotate(-1.5deg);
  }
  100% {
    -webkit-transform: translateY(-15px) rotate(1.5deg);
    transform: translateY(-15px) rotate(1.5deg);
  }
}
</style>
